// <auto-generated />
using System;
using AutomobileCatalog.Server.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomobileCatalog.Server.Core.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230211101359_Test1")]
    partial class Test1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutomobileCatalog.Server.Core.Make", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Makes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Toyota"
                        });
                });

            modelBuilder.Entity("AutomobileCatalog.Server.Core.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleColorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.HasIndex("VehicleColorId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MakeId = 2,
                            Name = "e220",
                            VehicleColorId = 1
                        },
                        new
                        {
                            Id = 2,
                            MakeId = 1,
                            Name = "e39",
                            VehicleColorId = 2
                        });
                });

            modelBuilder.Entity("AutomobileCatalog.Server.Core.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InitialPriceDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InitialPriceDate = new DateTime(2023, 2, 11, 12, 13, 59, 323, DateTimeKind.Local).AddTicks(1836),
                            Value = 19000m,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            InitialPriceDate = new DateTime(2023, 2, 11, 12, 13, 59, 323, DateTimeKind.Local).AddTicks(1867),
                            Value = 15000m,
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("AutomobileCatalog.Server.Core.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EngineCapacity")
                        .HasColumnType("float");

                    b.Property<int>("PriceId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The best car",
                            EngineCapacity = 2.0,
                            PriceId = 1,
                            VehicleModelId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Test description",
                            EngineCapacity = 1.6000000000000001,
                            PriceId = 2,
                            VehicleModelId = 2
                        });
                });

            modelBuilder.Entity("AutomobileCatalog.Server.Core.VehicleColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleColors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Чорний"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Білий"
                        });
                });

            modelBuilder.Entity("AutomobileCatalog.Server.Core.Model", b =>
                {
                    b.HasOne("AutomobileCatalog.Server.Core.Make", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutomobileCatalog.Server.Core.VehicleColor", "VehicleColor")
                        .WithMany("Models")
                        .HasForeignKey("VehicleColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Make");

                    b.Navigation("VehicleColor");
                });

            modelBuilder.Entity("AutomobileCatalog.Server.Core.Price", b =>
                {
                    b.HasOne("AutomobileCatalog.Server.Core.Vehicle", "Vehicle")
                        .WithMany("Price")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutomobileCatalog.Server.Core.Vehicle", b =>
                {
                    b.HasOne("AutomobileCatalog.Server.Core.Model", "VehicleModel")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("AutomobileCatalog.Server.Core.Make", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("AutomobileCatalog.Server.Core.Model", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("AutomobileCatalog.Server.Core.Vehicle", b =>
                {
                    b.Navigation("Price");
                });

            modelBuilder.Entity("AutomobileCatalog.Server.Core.VehicleColor", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
